int convert_int_to_fp(int n);
int convert_fp_to_int(int x);
int convert_fp_to_int_round(int x);
int fp_add(int x, int y);
int fp_sub(int x, int y);
int add_fp_int(int x,int n);
int sub_fp_int(int x,int n);
int fp_mul(int x, int y);
int mul_fp_int(int x,int n);
int fp_div(int x,int y);
int fp_int_div(int x,int n);
